// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Projekat.Migrations
{
    [DbContext(typeof(GlumacContext))]
    [Migration("20220115160538_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Models.Glumacc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("Godine");

                    b.Property<int>("Children")
                        .HasColumnType("int")
                        .HasColumnName("Broj Dece");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Prezime");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ime");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("Indeks");

                    b.Property<int>("NumberOfShows")
                        .HasColumnType("int")
                        .HasColumnName("Broj Predstavi");

                    b.HasKey("ID");

                    b.ToTable("Glumac");
                });

            modelBuilder.Entity("Models.Klijent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Email Klijenta");

                    b.Property<int?>("GlumacID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Prezime");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ime");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("Indeks");

                    b.HasKey("ID");

                    b.HasIndex("GlumacID");

                    b.ToTable("Klijent");
                });

            modelBuilder.Entity("Models.Predstava", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("GlumacID")
                        .HasColumnType("int");

                    b.Property<string>("ShowName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ime Predstave");

                    b.Property<int>("ShowNumber")
                        .HasColumnType("int")
                        .HasColumnName("Broj Predstave");

                    b.HasKey("ID");

                    b.HasIndex("GlumacID");

                    b.ToTable("Predstava");
                });

            modelBuilder.Entity("Models.Termin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("GlumacID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("Naziv Termina");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("Broj Termina");

                    b.Property<string>("Time")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Vreme");

                    b.HasKey("ID");

                    b.HasIndex("GlumacID");

                    b.ToTable("Termin");
                });

            modelBuilder.Entity("Models.Klijent", b =>
                {
                    b.HasOne("Models.Glumacc", "Glumac")
                        .WithMany("ListaKlijenta")
                        .HasForeignKey("GlumacID");

                    b.Navigation("Glumac");
                });

            modelBuilder.Entity("Models.Predstava", b =>
                {
                    b.HasOne("Models.Glumacc", "Glumac")
                        .WithMany("ListaPredstave")
                        .HasForeignKey("GlumacID");

                    b.Navigation("Glumac");
                });

            modelBuilder.Entity("Models.Termin", b =>
                {
                    b.HasOne("Models.Glumacc", "Glumac")
                        .WithMany("ListaTermina")
                        .HasForeignKey("GlumacID");

                    b.Navigation("Glumac");
                });

            modelBuilder.Entity("Models.Glumacc", b =>
                {
                    b.Navigation("ListaKlijenta");

                    b.Navigation("ListaPredstave");

                    b.Navigation("ListaTermina");
                });
#pragma warning restore 612, 618
        }
    }
}
